In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])

In [3]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.ones(3)

array([1., 1., 1.])

In [6]:
np.empty(3)

array([1., 1., 1.])

In [10]:
b = np.arange(0,12,2)

In [11]:
print(b)

[ 0  2  4  6  8 10]


In [12]:
arr = np.array([1,2,3,4,5,6])

In [13]:
print(arr)

[1 2 3 4 5 6]


In [14]:
np.append(arr, [7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6])

In [18]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6])

In [19]:
array_example = np.array([[[1,3,5],[7,9,11]],[[2,4,6],[8,10,12]]])

In [20]:
array_example

array([[[ 1,  3,  5],
        [ 7,  9, 11]],

       [[ 2,  4,  6],
        [ 8, 10, 12]]])

In [21]:
array_example.ndim

3

In [22]:
array_example.size

12

In [23]:
array_example.shape

(2, 2, 3)

In [32]:
c = np.arange(12)

In [33]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [34]:
d = c.reshape(2,2,3)

In [35]:
d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [36]:
e = np.array([1,2,3,4,5,6])

In [37]:
e

array([1, 2, 3, 4, 5, 6])

In [38]:
e.shape

(6,)

In [39]:
e2 = e[np.newaxis]

In [43]:
print(e2)
print(e2.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [44]:
row_vector = e[np.newaxis, :]

In [45]:
print(row_vector)
print(row_vector.shape)

[[1 2 3 4 5 6]]
(1, 6)


In [46]:
col_vector = e[:, np.newaxis]

In [47]:
print(col_vector)
print(col_vector.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


In [52]:
e3 = np.expand_dims(e, axis = 0)

In [53]:
print(e3)

[[1 2 3 4 5 6]]


In [56]:
print(e[e>4])

[5 6]


In [57]:
divisible_by_2 = e[e%2==0]

In [58]:
print(divisible_by_2)

[2 4 6]


In [60]:
divisible_by_3 = e[e%3==0]

In [61]:
print(divisible_by_3)

[3 6]


In [65]:
if 1 in e:
    logic = (e > 2)
else:
    logic = (e < 4)

In [66]:
print(logic)

[False False  True  True  True  True]


In [67]:
e4 = e[(e > 2) & (e < 6)]

In [68]:
print(e4)

[3 4 5]


In [69]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])

In [70]:
arr3 = arr2[3:8]

In [71]:
print(arr3)

[4 5 6 7 8]


In [72]:
a_1 = np.array([[1,1], [2,2]])
a_2 = np.array([[3,3], [4,4]])

In [76]:
vs = np.vstack((a_1, a_2))

In [77]:
print(vs)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [78]:
hs = np.hstack((a_1, a_2))
hs

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [80]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],[13,14,15,16,17,18,19,20,21,22,23,34]])
arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 34]])

In [86]:
hspl = np.hsplit(arrsplit, 6)
hspl

[array([[ 1,  2],
        [13, 14]]), array([[ 3,  4],
        [15, 16]]), array([[ 5,  6],
        [17, 18]]), array([[ 7,  8],
        [19, 20]]), array([[ 9, 10],
        [21, 22]]), array([[11, 12],
        [23, 34]])]

In [88]:
split = np.array(np.hsplit(arrsplit, 3))
split

array([[[ 1,  2,  3,  4],
        [13, 14, 15, 16]],

       [[ 5,  6,  7,  8],
        [17, 18, 19, 20]],

       [[ 9, 10, 11, 12],
        [21, 22, 23, 34]]])

In [95]:
coba = arrsplit.view()
coba

array([[ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 34]])

In [96]:
split.shape

(3, 2, 4)

In [97]:
contek = arrsplit.copy()
contek

array([[ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 34]])

In [93]:
arrsplit[0] = 5

In [94]:
arrsplit

array([[ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 34]])

In [98]:
a = np.array([1,2,3,4,5])

In [100]:
a.sum()

15

In [103]:
data = np.array([1,2])
data

array([1, 2])

In [104]:
ones = np.ones(2)
ones

array([1., 1.])

In [105]:
data - ones

array([0., 1.])

In [106]:
data + ones

array([2., 3.])

In [107]:
data * data

array([1, 4])

In [108]:
data / data

array([1., 1.])

In [109]:
data * 1.6

array([1.6, 3.2])

In [110]:
data.min()

1

In [111]:
data.max()

2

In [112]:
data.sum()

3

In [113]:
data.std()

0.5

In [114]:
metrices = np.array ([[1,2],[3,4]])
metrices

array([[1, 2],
       [3, 4]])

In [116]:
z = np.random.random((3,2))
z

array([[0.15904544, 0.19486427],
       [0.83630291, 0.384703  ],
       [0.80796661, 0.02061153]])

In [117]:
print(z.min())
print(z.max())
print(z.sum())
print(z.std())

0.02061152737860783
0.8363029136204895
2.403493759665822
0.31651864933370194


In [121]:
print(z[2,0])

0.8079666106521892


In [122]:
print(z.T)

[[0.15904544 0.83630291 0.80796661]
 [0.19486427 0.384703   0.02061153]]


In [124]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [125]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [126]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
arr = np.arange(6).reshape(3,2)
print(arr)

[[0 1]
 [2 3]
 [4 5]]


In [129]:
ndarr = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [130]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [131]:
print(np.empty((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [132]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [133]:
print(np.random.random((4,3,2)))

[[[0.22913007 0.62878006]
  [0.55285809 0.1650349 ]
  [0.9058499  0.23564278]]

 [[0.33929996 0.65190249]
  [0.78320483 0.15529637]
  [0.83042199 0.62775348]]

 [[0.32985513 0.85249778]
  [0.40621221 0.30690201]
  [0.41842076 0.26578635]]

 [[0.83116546 0.73859177]
  [0.7934611  0.754855  ]
  [0.90940855 0.05338631]]]


In [134]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])